/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserFeedback } from "./UserFeedback";
import { UserFeedbackCountArgs } from "./UserFeedbackCountArgs";
import { UserFeedbackFindManyArgs } from "./UserFeedbackFindManyArgs";
import { UserFeedbackFindUniqueArgs } from "./UserFeedbackFindUniqueArgs";
import { CreateUserFeedbackArgs } from "./CreateUserFeedbackArgs";
import { UpdateUserFeedbackArgs } from "./UpdateUserFeedbackArgs";
import { DeleteUserFeedbackArgs } from "./DeleteUserFeedbackArgs";
import { UserFeedbackService } from "../userFeedback.service";
@graphql.Resolver(() => UserFeedback)
export class UserFeedbackResolverBase {
  constructor(protected readonly service: UserFeedbackService) {}

  async _userFeedbacksMeta(
    @graphql.Args() args: UserFeedbackCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserFeedback])
  async userFeedbacks(
    @graphql.Args() args: UserFeedbackFindManyArgs
  ): Promise<UserFeedback[]> {
    return this.service.userFeedbacks(args);
  }

  @graphql.Query(() => UserFeedback, { nullable: true })
  async userFeedback(
    @graphql.Args() args: UserFeedbackFindUniqueArgs
  ): Promise<UserFeedback | null> {
    const result = await this.service.userFeedback(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserFeedback)
  async createUserFeedback(
    @graphql.Args() args: CreateUserFeedbackArgs
  ): Promise<UserFeedback> {
    return await this.service.createUserFeedback({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => UserFeedback)
  async updateUserFeedback(
    @graphql.Args() args: UpdateUserFeedbackArgs
  ): Promise<UserFeedback | null> {
    try {
      return await this.service.updateUserFeedback({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserFeedback)
  async deleteUserFeedback(
    @graphql.Args() args: DeleteUserFeedbackArgs
  ): Promise<UserFeedback | null> {
    try {
      return await this.service.deleteUserFeedback(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
